- inst/rmarkdown/templates/plos_article/skeleton/skeleton.Rmd
Note sure if this is meant to refer to `Pakillo/rmdTemplates` or this `rticles` packages. Works for me with `rticles`...
> RmdTemplates -> rticles

- inst/rmarkdown/templates/tufte_ebook/skeleton/skeleton.Rmd
Per the request I received-sorry for the delay...
> Removed dependency on papeR, which is no longer on CRAN.

- inst/rmarkdown/templates/ctex/skeleton/skeleton.Rmd
ctex has a major update about the font setting. Before a detailed review of new ctex package, this push could be worked properly for users.
> add a solution and instruction of ctex document

- R/jss_article.R
> use TeX plotting for JSS

- inst/rmarkdown/templates/jss_article/resources/template.tex
The commit allows changing documentclass and classoption of JSS template in the Rmd file.
> documentclass and classoption of JSS template.

- R/rjournal_article.R
> Fix preamble in RJournal template

- man/pnas_article.Rd
pnas_article roxygen is out of date with pnas_article.R
> add roxygen for pnas_article

- inst/rmarkdown/templates/pnas_article/resources/template.tex
- inst/rmarkdown/templates/pnas_article/skeleton/skeleton.Rmd
Also include lead_author_surname option and lineno option in the skeleton Rmd template.
> fix toggle for line numbering (lineno option)

- R/sim_article.R
- inst/rmarkdown/templates/sim_article/resources/template.tex
- inst/rmarkdown/templates/sim_article/skeleton/skeleton.Rmd
- inst/rmarkdown/templates/sim_article/skeleton/wileyj.bst
Hi,
I updated the template for Statistics in Medicine for a greater adherence to its LaTeX class. 
The template knits fine on my side, as before some tests do not succeed.
Thanks!
> Updated the SiM template

- inst/rmarkdown/templates/sim_article/resources/template.tex
- inst/rmarkdown/templates/sim_article/skeleton/skeleton.Rmd
Apologies @jjallaire for a new pull request - I found myself needing this option and I added it to the template as well.
Best wishes,
Alessandro
> Added support for 'doublespace' option of simauth class

- inst/rmarkdown/templates/asa_article/resources/template.tex
Sorry about the branch name. I apparently don't have permission to create and push a branch to this repo, and then make a PR. But because I am a member of RStudio, the GitHub UI won't let me make a fork either. I had to force the fork through unusual means, then change the commits involved.
> Make links and lists work in TAS template

- inst/rmarkdown/templates/asa_article/resources/template.tex
Allows for custom LaTeX declarations similar to rjournal.
> Adds a preamble variable to asa template

- R/peerj_article.R
- README.md
- inst/rmarkdown/templates/peerj_article/resources/template.tex
- inst/rmarkdown/templates/peerj_article/skeleton/sample.bib
- inst/rmarkdown/templates/peerj_article/skeleton/wlpeerj.cls
- man/peerj_article.Rd
I have updated the PeerJ article citation format to be more pandoc-tic.
> Update peerj article citation format

- R/jss_article.R
Setting options infects the current session, and doesn't seem necessary here
> Use jss prompt and continue directly

- inst/rmarkdown/templates/jss_article/skeleton/jss.cls
- inst/rmarkdown/templates/mdpi_article/skeleton/mdpi.cls
- inst/rmarkdown/templates/mnras_article/skeleton/mnras.cls
- inst/rmarkdown/templates/rsos_article/skeleton/rsos.cls
- inst/rmarkdown/templates/sim_article/skeleton/WileyNJD-v2.cls
@yihui: Thanks for merging #189. Here are the other suggested updates.
> Point new DOI hyperlinks to preferred resolver

- NEWS.md
- R/copernicus_article.R
- inst/rmarkdown/templates/copernicus_article/resources/template.tex
- inst/rmarkdown/templates/copernicus_article/skeleton/skeleton.Rmd
> Add defining multiple corresponding authors for Copernicus

- inst/rmarkdown/templates/agu_article/resources/template.tex
- inst/rmarkdown/templates/agu_article/skeleton/skeleton.Rmd
Some AGU journals require a Plain Language Summary.
> Adds plain language summary for agu_article

- inst/rmarkdown/templates/jss_article/resources/template.tex
- inst/rmarkdown/templates/jss_article/skeleton/skeleton.Rmd
fix warning reported by https://github.com/rstudio/rticles/issues/219
> fix warning reported by issue-219

- NEWS.md
- inst/rmarkdown/templates/ieee_article/resources/template.tex
- inst/rmarkdown/templates/ieee_article/skeleton/skeleton.Rmd
Added support for Keywords field.
> IEEE Trans: added keywords support

- README.md
closes #249 
I think it does no harm to add more Getting started information in the README. 
In doubt, here is a PR instead of pushing to master directly.
> Document better how to contribute

- .travis.yml
This should fix the timeout problem on travis.
List based on setdiff with tinytex::tl_pkgs() before and after running tests.
> install all required packages for testing rticles

- NEWS.md
- inst/rmarkdown/templates/rjournal/resources/template.tex
> [rjournal] insert newline at correct place in template

- NEWS.md
- inst/rmarkdown/templates/bioinformatics/resources/template.tex
- inst/rmarkdown/templates/bioinformatics/skeleton/skeleton.Rmd
fixes #414
To contribute a new article template to this package, please make sure you have done the following things (note that `journalname_article` below is only an example name):
You could also, unless you have done it in any other RStudio's projects before, sign the [individual](https://rstudioblog.files.wordpress.com/2017/05/rstudio_individual_contributor_agreement.pdf) or [corporate](https://rstudioblog.files.wordpress.com/2017/05/rstudio_corporate_contributor_agreement.pdf) contributor agreement. You can send the signed copy to <jj@rstudio.com>.
Lastly, please try your best to do only one thing per pull request (e.g., if you want to add two output formats, do them in two separate pull requests), and refrain from making cosmetic changes in the code base: …
> bioinformatics: use subject_section in header

- DESCRIPTION
- NEWS.md
- inst/rmarkdown/templates/tf/resources/template.tex
> Allow classoptions

- NEWS.md
- inst/rmarkdown/templates/acs/resources/template.tex
- inst/rmarkdown/templates/aea/resources/template.tex
- inst/rmarkdown/templates/agu/resources/template.tex
- inst/rmarkdown/templates/amq/resources/template.tex
- inst/rmarkdown/templates/ams/resources/template.tex
- inst/rmarkdown/templates/bioinformatics/resources/template.tex
- inst/rmarkdown/templates/lipics/resources/template.tex
- inst/rmarkdown/templates/mnras/resources/template.tex
- inst/rmarkdown/templates/pnas/resources/template.tex
- inst/rmarkdown/templates/rsos/resources/template.tex
- inst/rmarkdown/templates/rsos/skeleton/skeleton.Rmd
- inst/rmarkdown/templates/rss/resources/template.tex
- inst/rmarkdown/templates/sage/resources/template.tex
- inst/rmarkdown/templates/sim/resources/template.tex
This should fix the current CI issue with Pandoc devel. 
Not sure though why it has affected only rsos template 🤔
> Add highlighting-macros to all templates

- DESCRIPTION
- NEWS.md
- R/copernicus_article.R
- inst/rmarkdown/templates/copernicus/resources/README_copernicus_package_6_3.txt
- inst/rmarkdown/templates/copernicus/resources/template.tex
- inst/rmarkdown/templates/copernicus/skeleton/copernicus.cfg
- inst/rmarkdown/templates/copernicus/skeleton/copernicus.cls
- man/copernicus_article.Rd
Just another update of the Copernicus `rticles` template. @nuest
> Update Copernicus Publication template to version 6.3

- DESCRIPTION
- NEWS.md
- inst/rmarkdown/templates/elsevier/resources/template.tex
following Pandoc's default template
Fix #421
> Update elsevier template for tables

- DESCRIPTION
- inst/rmarkdown/templates/jedm/skeleton/skeleton.Rmd
Thanks for your final touch, @cderv! This PR updates my information (e.g., email; affiliation) following #251.
> Updated JooYoung's info

- .github/workflows/R-CMD-check.yaml
- tests/testit/test-formats.R
> Debug the glossa issue

- DESCRIPTION
- NEWS.md
- inst/rmarkdown/templates/sage/resources/template.tex
set citestyle to comma to match the Sage Havard style. see: https://github.com/rstudio/rticles/issues/447
To contribute a new article template to this package, please make sure you have done the following things (note that `journalname_article` below is only an example name):
You could also, unless you have done it in any other RStudio's projects before, sign the [individual](https://rstudioblog.files.wordpress.com/2017/05/rstudio_individual_contributor_agreement.pdf) or [corporate](https://rstudioblog.files.wordpress.com/2017/05/rstudio_corporate_contributor_agreement.pdf) contributor agreement. You can send the signed copy to <jj@rstudio.com>.
Lastly, please try your best to do only one thing per pull request (e.g., if you want to add two output formats, do them in two separate pull …
> set citestyle to comma in `sage_article()` per guideline

- .github/workflows/pkgdown.yaml
- DESCRIPTION
- NEWS.md
- R/article.R
- tests/testit/test-formats.R
- vignettes/articles/examples.Rmd
Try to see why one template is not shown in gallery
> Fix examples page building

- NEWS.md
- R/copernicus_article.R
- inst/rmarkdown/templates/copernicus/resources/README_copernicus_package_6_5.txt
- inst/rmarkdown/templates/copernicus/skeleton/copernicus.cfg
- inst/rmarkdown/templates/copernicus/skeleton/copernicus.cls
- man/copernicus_article.Rd
Another update of the Copernicus template release before Christmas. 
@nuest
> Copernicus template update to version 6.5

- NEWS.md
- R/copernicus_article.R
- inst/rmarkdown/templates/copernicus/resources/README_copernicus_package_6_7.txt
- inst/rmarkdown/templates/copernicus/skeleton/copernicus.bst
- inst/rmarkdown/templates/copernicus/skeleton/copernicus.cls
- man/copernicus_article.Rd
Here is another Copernicus template update. @nuest
> Copernicus template update to version 6.7

- NEWS.md
- R/copernicus_article.R
- inst/rmarkdown/templates/copernicus/resources/README_copernicus_package_7_2.txt
- inst/rmarkdown/templates/copernicus/resources/template.tex
- inst/rmarkdown/templates/copernicus/skeleton/copernicus.cfg
- man/copernicus_article.Rd
Another update of the Copernicus template @nuest.
> Copernicus template update from 7.1 -> 7.2

- NEWS.md
- R/copernicus_article.R
- inst/rmarkdown/templates/copernicus/resources/README_copernicus_package_7_3.txt
- inst/rmarkdown/templates/copernicus/resources/template.tex
- inst/rmarkdown/templates/copernicus/skeleton/copernicus.cfg
- man/copernicus_article.Rd
And yet another Copernicus template update from version 7.2 to 7.3 @nuest
> Template update 7.2 -> 7.3
