- R/jss_article.R
The LaTeX template scales the figures to 80% of the text width, which is [defined](https://github.com/rstudio/rticles/blob/master/inst/rmarkdown/templates/jss_article/skeleton/jss.cls#L75) as 6.125". For best results, figures should be inserted using their natural size. In addition, figures are centered, and the pointsize device option is set to match the point size of the document.
> Sensible defaults for figures in JSS paper

- inst/rmarkdown/templates/acm/resources/template.tex
- inst/rmarkdown/templates/acs/resources/template.tex
- inst/rmarkdown/templates/jss_article/resources/template.tex
- inst/rmarkdown/templates/plos_article/resources/template.tex
- inst/rmarkdown/templates/use_r_abstract/resources/template.tex
For consistency. I'm not sure if this is really allowed by the affected journals -- if not, we might need to look for another solution, as pandoc will create UTF-8 anyway.
> use UTF-8 as input encoding

- inst/rmarkdown/templates/rjournal_article/resources/template.tex
In general, latex commands of the form
```
\foo{
```
Should be replaced with
```
\foo{%
```
to avoid an unwanted whitespace token getting inserted.
I've fixed this in the R Journal article template since it was causing the authors names to be preceded by an unwanted space.  This issue may affect other templates, but I haven't used them.
> Fix unwanted space in authors list

- inst/rmarkdown/templates/rjournal_article/skeleton/skeleton.Rmd
It seems that the author guide location on the R Journal website has moved. This modifies the skeleton to point to the correct link.
> Fix broken link

- inst/rmarkdown/templates/elsevier_article/skeleton/skeleton.Rmd
Updates Elsevier skeleton to add `address` and `footnote` examples.
See https://github.com/rstudio/rticles/issues/64
> Add address and footnote examples to Elsevier skeleton.

- inst/rmarkdown/templates/elsevier_article/resources/template.tex
This is required for compatibility with pandoc >= 1.14.
This fix complements d1fa8547660d3d2fa68f9b4998c1e0bde0b1eb35
> Add \tightlist macro to elsevier format

- R/jss_article.R
This fixes the problem that `jss_article` doesn't show the R prompts.  It sets the default prompt to "R> ", with continuation as "R+ ", but allows the document to change these settings.
> Fix issue 61 and part of 71

- R/jss_article.R
Fixes the problem that pandoc creates a tex file with \end{CodeOutput}\begin{CodeInput} in same line that raises this error with pdflatex: "! FancyVerb Error: Extraneous input `\begin{CodeInput}\end{}' between \end{CodeOutput} and line end".
> Ensure empty line between environments.

- inst/rmarkdown/templates/aea_article/resources/template.tex
- inst/rmarkdown/templates/aea_article/skeleton/skeleton.Rmd
Fixes #86 by allowing default content to be edited in skeleton.Rmd
> move default content to skeleton

- inst/rmarkdown/templates/sim_article/resources/template.tex
- inst/rmarkdown/templates/sim_article/skeleton/skeleton.Rmd
Hi!
I updated the template and removed the dependency on `mathtime.sty`. Now it should build fine, `devtools::check()` runs well on my Mac:
```
[...]
R CMD check results
0 errors | 0 warnings | 1 note 
R CMD check succeeded
```
The note is:
```
checking for GNU extensions in Makefiles ... NOTE
GNU make is a SystemRequirements.
```
Some tests still fail on a IT managed Windows computer: I get warnings for more or less all formats and an error for `pnas_article_format`, `@test_formats.R#30`.
/cc @jjallaire
> Removed dependency on 'mathtime' for SiM template

- inst/rmarkdown/templates/sim_article/resources/template.tex
- inst/rmarkdown/templates/sim_article/skeleton/skeleton.Rmd
Hi!
I added support for custom tables packages to the Statistics in Medicine template, via adding the `header-includes` option in the YAML header.
Best wishes,
Alessandro
> Tables in SiM template

- inst/rmarkdown/templates/elsevier_article/resources/template.tex
The
```
$for(header-includes)$
$header-includes$
$endfor$
```
construction was present twice in the template for `elsevier_article`. This causes problems when, say, what is being included is a file with macro definitions, since the macros get defined twice, causing an error.
> header-includes were being included twice in the elsevier template.

- inst/rmarkdown/templates/jss_article/resources/template.tex
It looks like some of the templates support `header-includes`, while others support `preamble`, and a few (including JSS, now) support both.
> Added handling of header-includes to the jss_article template.

- R/sim_article.R
- README.md
- inst/rmarkdown/templates/sim_article/resources/template.tex
- inst/rmarkdown/templates/sim_article/skeleton/skeleton.Rmd
- man/sim_article.Rd
I added the explicit option for loading the LaTeX longtable package (see #126). I also expanded the documentation with all the possible YAML options.
> Added explicit longtable option

- inst/rmarkdown/templates/ieee_article/resources/template.tex
`endfloat` package is not in IEEETran. If needed it can be added in the header.
> remove endfloat package

- inst/rmarkdown/templates/ctex/resources/default.latex
prevent extra spaces between Chinese and non-Chinese characters in code blocks
the same issue like here https://github.com/yihui/bookdown-chinese/commit/c70ef766b117f3
and here https://stackoverflow.com/q/47990152/559676
> prevent extra spaces between Chinese and non-Chinese characters in code blocks

- inst/rmarkdown/templates/elsevier_article/resources/template.tex
This small fix removes a trailing comma which occures in the keywords list.
> fix sep in keywords line in Elsevier template

- DESCRIPTION
Otherwise `document()` fails for me (on `amq_article()`)
> Set package encoding to utf-8

- inst/rmarkdown/templates/ieee_article/resources/template.tex
Using the ieee_article template from 7708443062fb8c3bd06f9ccda77cbd003d9ff5a5, using an ordered list in the Rmarkdown:
```
1. foo
2. bar
```
results in the following error (from pdflatex) when generating a PDF: 
```
! Undefined control sequence.
l.696 \tightlist
```
Copying the \tightlist macro definition from the template.tex in another format into the ieee_article template.tex resolved the issue (though I'm not sure if there's a more preferable spot in template.tex to put the \tightlist definition).
> Add \tightlist macro to ieee_article

- inst/rmarkdown/templates/acm_article/resources/template.tex
- inst/rmarkdown/templates/aea_article/resources/template.tex
- inst/rmarkdown/templates/amq_article/resources/template.tex
- inst/rmarkdown/templates/asa_article/resources/template.tex
- inst/rmarkdown/templates/mdpi_article/resources/template.tex
- inst/rmarkdown/templates/rjournal_article/resources/template.tex
- inst/rmarkdown/templates/rss_article/resources/template.tex
- inst/rmarkdown/templates/springer_article/resources/template.tex
See #90. This passes tests on my machine, though I haven't added tests to confirm header-includes are working. I get some warnings about "input string XXX is invalid in this locale".
> Add header-includes to various TeX templates

- inst/rmarkdown/templates/rss_article/resources/template.tex
Loosely following the way this seems to work in the JSS articles, I have added an optional `[classoption]` element that can be triggered by using `classoption:` in an Rmd file's YAML header.
> Enable setting classoption in RSS article type

- inst/rmarkdown/templates/acm_article/skeleton/skeleton.Rmd
The DOI foundation recommends [this new resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). Yes, a bit ironic that they would change the URL of their service, but it's now [encrypted](https://www.ssllabs.com/ssltest/analyze.html?d=doi.org). Because the old links with the `dx` subdomain continue to work, there is no urgent need to do anything.
However, I'd hereby like to suggest to follow the new recommendation and update the demo  link.
PS: Since this is similar to a typo fix, I didn't consider the PR template checklist applicable.
> Promote new, preferred DOI resolver

- inst/rmarkdown/templates/ieee_article/resources/template.tex
- inst/rmarkdown/templates/ieee_article/skeleton/skeleton.Rmd
I am writing an article where some authors have no `department` which would result in a blank line:
This little  proposal make it possible to avoid the (ugly) blank line:
> IEEETrans authors layout enhancements

- inst/rmarkdown/templates/pnas_article/resources/template.tex
When `keyword` is not availabe, and extra `}` is created, which causes the tex file to fail to compile.
> Fixed keyword bug in PNAS

- inst/rmarkdown/templates/aea_article/resources/template.tex
`acknowledgements` was spelled wrong
> Fixed typo

- inst/rmarkdown/templates/ieee_article/resources/template.tex
Fixed a tiny issue with institution columnar mode: institution deprtment and institution name are now in the correct order
> tiny fix: swapped institution department and name in institution-columnar

- inst/rmarkdown/templates/agu_article/skeleton/skeleton.Rmd
I'm trying to automate checking if keywords are less than 100 characters. Do you think this approach is ok? If it detects that some keypoints have more than 100 characters, it prints a red warning in the document:
I didn't want to make it an error because in I would think that during the drafting process it's common to have a long keypoint that you will shorten later. Throwing a `warning()` is not useful because it gets lost in the sea of knitr messages. I wanted to add the warning at the end of each keyword, but `rmarkdown::metadata$keywords <- things` throws an error. This is the next best thing I came up with.
> Adds 100 character warning to AGU article

- inst/rmarkdown/templates/agu_article/resources/template.tex
I realised that the AGU template didn't work properly when using multiple files in `bibliography`.
> Adds support for multiple bib files

- inst/rmarkdown/templates/rss_article/template.yaml
A simple error in the name of the template. The RSS is not the Royal Society of Statistics. It is the Royal Statistical Society.
> Royal Statistical Society, not Royal Soc of Stats

- NEWS.md
- inst/rmarkdown/templates/elsevier_article/resources/template.tex
The option `citation_package: natbib` in the elsevier_article was not possible because the template initialized two bibliographystyles. In addition to that the parameter `bibliography` was not recognized because it was names `biblio-files` in the template.
Furthermore I removed the biblatex commands, because in the elsevier_article class no biblatex support is given and will always give an error.
The only restriction is to name the bibliography file *without* the extension *.bib due to the construction of natbib.
> edited elsevier_article to use with natbib

- NEWS.md
- R/copernicus_article.R
- inst/rmarkdown/templates/copernicus_article/resources/README_copernicus_package_5_3.txt
- inst/rmarkdown/templates/copernicus_article/resources/template.tex
- inst/rmarkdown/templates/copernicus_article/skeleton/copernicus.cfg
- inst/rmarkdown/templates/copernicus_article/skeleton/copernicus.cls
- inst/rmarkdown/templates/copernicus_article/skeleton/skeleton.Rmd
- man/copernicus_article.Rd
- add video supplement
- add sample availability
- add journals: deuquasp, gchron
> Update Copernicus Publications template to version 5.3

- inst/rmarkdown/templates/copernicus_article/resources/template.tex
After the first authors started using the template, I discussed "detecting" submissions based on rticles on the side of the publisher. They would be interested to learn how many authors use the template and have added the flag added by this PR to their publication system to be automatically detected.
No rush, but would be great if this could be included in the next release.
> add unambiguous flag for Copernicus template detection

- R/ieee_article.R
- man/ieee_article.Rd
Fix lack of propagation of arguments to base formats.
A symptom of the issue was the failure to include extra settings via `in_header` when using something like:
```
output:
bookdown::pdf_book:
base_format: rticles::ieee_article
```
> ieee_article: Fix lack of propagation of arguments to base formats.

- inst/rmarkdown/templates/elsevier_article/resources/template.tex
- inst/rmarkdown/templates/elsevier_article/skeleton/skeleton.Rmd
Updated the template for elsevier_article to allow for two authors to share the same footnote (e.g. "these authors made equal contributions") and updated the corresponding skeleton to demonstrate how to use a shared footnote. To do this, I mimicked the style of shared affiliations. (This is my first pull request to an RStudio repo. Any feedback you have for me would be much appreciated!)
> Added shared footnotes to elsevier_article()

- NEWS.md
- inst/rmarkdown/templates/springer_article/resources/template.tex
- inst/rmarkdown/templates/springer_article/skeleton/skeleton.Rmd
As springer latex offers support for 3 kind of bibliography styles, it would be nice to have the possibility to modify it with a variable *bibstyle*.
If no variable is defined, the default goes to *spbasic*.
> Add support for bibliography styles on springer template

- DESCRIPTION
- NEWS.md
- inst/rmarkdown/templates/ieee_article/resources/template.tex
- inst/rmarkdown/templates/ieee_article/skeleton/skeleton.Rmd
Hello, 
I wrote an IEEE article using the rticles templates and I needed to custom the sorting order of the citations to be 1, 2, 3...
I modified the template this way and added a citation_sorting option in Index.Rmd yaml section. I think there may be a better solution (for example as a subitem of the citation_package option) but I wanted not to modify the previous options as possible.
> Sorting bibliography

- inst/rmarkdown/templates/springer_article/resources/template.tex
- inst/rmarkdown/templates/springer_article/skeleton/skeleton.Rmd
1. The springer Rmd template had several issues that didnt allow the proper implementation of the reference style selected by the user.
- Pandoc doesnt translate markdown references (e.g. @AuthorB) to latex in the form of \cite, it translates them into \textcite{AuthorB} or \autocite{AuthorB}, which results in the creation of generic csl templated references before the actual bibliography.
- Because of the generation of those csl references, the biblatex references where not generated and the style did not change regardless of the user setting.
In order to modify this behavior, instead of the @AuthorB style, i suggest that the classic latex \cite{AuthorB} should be used. With it, these false csl references are not generated and the style of the references can be controlled with the …
> Springer template modifications for correct reference functionality

- inst/rmarkdown/templates/joss_article/skeleton/skeleton.Rmd
This is a small change to the [JOSS](https://joss.theoj.org/) paper template to remove the `formatted_doi` field which causes production issues for JOSS and is not actually a field that we [ask for in our template](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography).
More specifically, by including this field, the value associated overrides the parameter when it's being passed in by the JOSS Whedon bot.
This issue arose in https://github.com/openjournals/joss-reviews/issues/2028#issuecomment-578242951 when the `formatted_doi` field was left blank by the submitting author @embruna. 
Fixes https://github.com/openjournals/joss/issues/672
> Removing formatted_doi field from JOSS template.

- NEWS.md
- inst/rmarkdown/templates/biometrics_article/resources/template.tex
A friend of mine brought to my attention that the biometrics template lacks the header-includes loop. Here is the fix. Thanks! :)
> Added missing header-includes for the Biometrics template

- inst/rmarkdown/templates/ctex/skeleton/skeleton.Rmd
编译 rticles 自带的 ctex 中文 R Markdown 模版，目前已经出现如下警告
```
Warning message:
Package ctex Warning: Option `hyperref' is deprecated.
(ctex)                `hyperref' package will be loaded.
```
可见 hyperref 类选项已经 deprecated，上游 ctex 文类会自动加载 hyperref 宏包，所以不再需要它了。
> * hyperref 类选项已经 deprecated，hyperref 宏包会自动加载，所以不再需要它了。

- R/jss_article.R
- inst/rmarkdown/templates/jss_article/skeleton/skeleton.Rmd
#254
> **Continuation prompts**
> 
> At the moment rticles employs either R+ (for evaluated code) or R> (for non-evaluated code) as the continution prompt but + would be requested by JSS.
The code chunk
```{r}
f(a = 1,
b = 2)
```
now correctly renders as the journal template example
```
R> f(a = 1,
+    b = 2)
```
> **Inline code formatting**
> 
> For code in Markdown it is ok to use backtick syntax, so that `\code{...}` is typically not necessary. Hence I it is ok to remove `\code{print("abc")}` from `skeleton.Rmd`, I think.
Changed the way markdown backtick syntax renders to `\code{}` instead of `texttt{}` and documented in the `skeleton.Rmd`
> Implemented some of the suggestions from #254 to jss_article

- DESCRIPTION
- NEWS.md
- R/jss_article.R
In some cases, when using authors in multiple lines with the `\AND` command (see #100 and https://github.com/rstudio/rticles/commit/b740b19b90cd6f7afe2cd7d66456c9efa0bb4cdf), the TeX file will result in `\AND \And` at the start of a new line (example shown below). This makes 
```r
x <- gsub('( \\\\AND )\\\\And ', '\\1', x)
``` 
replacement not able to get rid of `\And`. This small fix is able to handle this special case as well as the previous replacement cases.
```tex
\author{
Main author\\University of life and more \And Second author\\University
of life and more \And Third Author\\University of life and more
\AND \And Fourth Author\\University of life and more \And Fifth
Author\\University of life and more \And Sixth Author\\University of
life and more \AND Seventh Author\\University …
```
> Better JSS multiline author support

- NEWS.md
- inst/rmarkdown/templates/elsevier_article/resources/template.tex
This will close #300
A renewcommand on `\includegraphics` setting a `width=\maxwidth` was preventing to use chunk option `out.width`
> Fix figure width setting in elsevier article

- R/jss_article.R
Closes #311 
This currently uses unexported function
> Correctly add continue prompt when eval = FALSE

- NEWS.md
- inst/rmarkdown/templates/jss_article/resources/template.tex
- inst/rmarkdown/templates/jss_article/skeleton/skeleton.Rmd
This will close #291 
This new `affiliation2` field will be used instead of `affiliation` if provided. This allow to provide  a differently formated affiliation if necessary to be used in the Adress part of the template. 
Ex: with a newline in author field and not newline in adresse field.
From the example in #291 
````md
---
documentclass: jss
author:
- name: Alfredo Hernández
affiliation: |
| Universitat Autònoma 
| de Barcelona
address: |
| Department of Statistics and Mathematics,
| Faculty of Biosciences,
| Universitat Autònoma de Barcelona
affiliation2: Universitat Autònoma de Barcelona
email: \email{aldomann.designs@gmail.com}
url: \url{aldomann.com}
- name: David Endesfelder
affiliation: Bundesamt für Strahlenschutz
- name: Joan Francesc Barquinero
affiliation: |
| Universitat …
```
> add a affiliation2 field in JSS template

- DESCRIPTION
I was conservative and only set the minimum working version for latex-div.lua to work. 
We could be more up to date and set to `>= 2.3`, the last CRAN version. 
I opened the PR so that you can advice and choose.
> set rmarkdown minimum requirement to 1.16 so that latex-div.lua is available

- NEWS.md
- R/copernicus_article.R
- inst/rmarkdown/templates/copernicus/resources/README_copernicus_package_6_0.txt
- inst/rmarkdown/templates/copernicus/resources/template.tex
- inst/rmarkdown/templates/copernicus/skeleton/copernicus.cfg
- inst/rmarkdown/templates/copernicus/skeleton/copernicus.cls
Update Copernicus Publications template as discussed previously and, hopefully, sanitize #331 until a new version gets released by Copernicus. I tested the fix on my machine and it works as expected.
*Note: If I run the checks, some tests throw errors, however, none of them related to the Copernicus template.*
> Update Copernicus template to 6.0 and sanitize #331

- inst/rmarkdown/templates/jss/resources/template.tex
Same fix as in  36f461dc3efae883369a88086761318848e522b0 by pining the latexrelease package to older version (https://topanswers.xyz/tex?q=1416)
This should close #329  and fix the travis build https://github.com/rstudio/rticles/pull/335#issuecomment-710149989
let's see what travis think of that
> Fix JSS template by pinning the version of latexrelease package

- DESCRIPTION
- NEWS.md
- inst/rmarkdown/templates/ams/resources/template.tex
As written, the authors block is never closed when there is no `\currentaddress for author 2`. I've also moved the closing $endif$ for $if(author1)$ so that we don't end up with a stray brace when no authors are specified.
> AMS template.tex: Fix brace in author2

- NEWS.md
- README.md
- inst/rmarkdown/templates/copernicus/resources/README_copernicus_package_6_1.txt
- inst/rmarkdown/templates/copernicus/resources/template.tex
- inst/rmarkdown/templates/copernicus/skeleton/copernicus.cls
This PR includes the already announced final fix for #331, which was released by Copernicus today in the morning.
> Update Copernicus template to version 6.1

- NEWS.md
- inst/rmarkdown/templates/arxiv/resources/template.tex
- inst/rmarkdown/templates/arxiv/skeleton/skeleton.Rmd
Related to #345
The arxive template didn't have the holy 
```
$for(header-includes)$
$header-includes$
$endfor$
```
it also had biblyographystyle hardcoded.
> Adds some more variables to arxive template

- NEWS.md
- inst/rmarkdown/templates/springer/resources/template.tex
- inst/rmarkdown/templates/springer/skeleton/skeleton.Rmd
Following on this comment
https://github.com/rstudio/rticles/pull/356#discussion_r544181296
This changes the variable name from bibstyle to biblio-style to match the default pandoc template for latex and other rticles templates.
> Uses biblio-style instead of bibstyle in springer_article

- NEWS.md
- inst/rmarkdown/templates/copernicus/resources/template.tex
- inst/rmarkdown/templates/copernicus/skeleton/skeleton.Rmd
This pull request addresses a minor issue in the Copernicus template LaTeX file, placing the copyright statement further down.
I am currently co-authoring a manuscript for a Copernicus journal. Our manuscript was accepted for a public discussion. However, it bounced back to us during the file validation step. The email we received from the Copernicus office said: 
> I would like to inform you that the copyright statement should appear in the data/code availability section or wherever the data is mentioned in the preprint. 
Hence, I modified the `template.tex` accordingly and tested it. It seems fine now. Still, @nuest perhaps you want to double-check the amendment since you created the template? 
Modified files:
- `template.tex`
- `NEWS.md` (including a minor typo correction in an old …
> Copernicus template additional information on copyright statement

- .github/workflows/R-CMD-check.yaml
* use pak for speed and prevent mac bin issues
* use setup-tinytex@v1
* udpate pandoc version to 2.11.4
* regroup session information
> Update R CMD workflow

- DESCRIPTION
- NEWS.md
- R/copernicus_article.R
- inst/rmarkdown/templates/copernicus/resources/template.tex
- inst/rmarkdown/templates/copernicus/skeleton/skeleton.Rmd
- man/copernicus_article.Rd
Yet another update for the Copernicus Publication template after the `*.tex` produced by 'rticles' bounced back from the journal's office telling that additional LaTeX packages and commands are not supported. This was caused by the default syntax highlight enabled in `rmarkdown::pdf_document()`, which uses additional LaTeX commands.
To ensure that this update aligns with the publisher guidelines, I first discussed with @nuest via email and then contacted the journal's office before making this update (@nuest was in CC). 
Hence, this update ensures that the publisher will accept the `*.tex` produced by the templates without requiring further manual changes by the authors.  
**More details**
* The template now supports the `highlight` parameter of `rmarkdown::pdf_document()`. The default is …
> Copernicus template update - fixes syntax highlight problem

- NEWS.md
- inst/rmarkdown/templates/elsevier/resources/template.tex
This is a minor commit that exposes the bookdown `biblio-style` argument to the `elsarticle` LaTeX template when using natbib.
> Expose biblio-style in elsarticle

- NEWS.md
- R/article.R
- inst/rmarkdown/templates/lipics/skeleton/skeleton.Rmd
This fixes #392 (cc @nuest)
This can now be used in YAML 
```
output:
bookdown::pdf_book:
base_format: rticles::lipics_article
```
and it will no more error with 
```
! LaTeX Error: Command \theorem already defined.
Or name \end... illegal, see p.192 of the manual.
``` 
This change set an option for opting out the addition by **bookdown** of some definition. This requires **bookdown** 0.23 (currently dev version) to work
```r
remotes::install_github("rstudio/bookdown")
```
@yihui 
* is this how you would do it ? I used the `on_exit` argument to be sure to reset the options after `render()`
* I did not set a requirement for **bookdown**  up in DESCRIPTION as it is in suggest, should I ? 
* This requires **bookdown** 0.23, should we merge in **rticles** only when it is release ? I added a …
> Opt-out bookdown environment definition for lipic article

- DESCRIPTION
- NEWS.md
- inst/rmarkdown/templates/frontiers/skeleton/skeleton.Rmd
Hi there, love the package. I have been using it to typeset an article for Frontiers, and found a solution to moving the references to under the "References" header in Rmarkdown rather than at the end of the document. The solution was found from Andrew Morris' answer to [this stackoverflow](https://stackoverflow.com/questions/28815781/how-to-move-the-bibliography-in-markdown-pandoc) question. Hope this helps!
> changes reference location in Frontiers template

- NEWS.md
- R/copernicus_article.R
- inst/rmarkdown/templates/copernicus/resources/README_copernicus_package_6_4.txt
- inst/rmarkdown/templates/copernicus/resources/template.tex
- inst/rmarkdown/templates/copernicus/skeleton/copernicus.cfg
- man/copernicus_article.Rd
Another update of the Copernicus template (now version 6.4) and I've added a so far missing journal ("Web Ecology") to `copernicus_article()`
> Update Copernicus to v6.4 and add missing Copernicus journal

- NEWS.md
- R/copernicus_article.R
- inst/rmarkdown/templates/copernicus/resources/README_copernicus_package_6_6.txt
- inst/rmarkdown/templates/copernicus/resources/template.tex
- inst/rmarkdown/templates/copernicus/skeleton/copernicus.cfg
- man/copernicus_article.Rd
And yet another template updated based on the template released 18th January 2022. @nuest
> Copernicus template update to 6.6

- DESCRIPTION
- NEWS.md
- inst/rmarkdown/templates/jss/resources/template.tex
- inst/rmarkdown/templates/jss/skeleton/jss.cls
- inst/rmarkdown/templates/jss/skeleton/skeleton.Rmd
I noticed that the JSS jss.cls file had been updated.
This PR
- updates jss.cls to use last year's updated version [here](https://www.jstatsoft.org/public/journals/1/jss-article-tex.zip)
- adds `\orcidlink{}` to each author if `orcid:` specified in the Rmd YAML header
- adds missing `\usepackage{}` line to template.tex from the JSS article.tex example file.
(Nb. I have no affiliation to the journal, I was just using the current **rticles** version and noticed that it was 1 version behind.)
> Update Journal of Statistical Software template and class file

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
Updating to point to the current CLA PDFs on rstudio.com, and to change email address people should send them to.
More on this at: https://github.com/rstudio/rstudio/issues/10609
> Update CLA links and email alias

- NEWS.md
- R/copernicus_article.R
- inst/rmarkdown/templates/copernicus/resources/README_copernicus_package_6_8.txt
- inst/rmarkdown/templates/copernicus/skeleton/copernicus.cls
- man/copernicus_article.Rd
Sorry, and yet another update of the Copernicus template (@nuest). Yesterday, I must have just downloaded the latest version while an even newer version came probably online just minutes or hours later. 
Interesting: Now they finally support the LaTeX `listings` package, but adding "--listings" as an additional pandoc argument does not seem to work. Moreover, it is part of the *.cls file but not (yet) mentioned in their template file. We should watch it and add this with another update once also the LaTeX template mentions this option.
> Copernicus Template Update 6.8

- NEWS.md
- R/jss_article.R
Fix #476 by taking into account options$indent in JSS article special hooks
> Fix nested code chunk in markdown list for `jss_article()`

- DESCRIPTION
- NEWS.md
- inst/rmarkdown/templates/glossa/skeleton/glossa.bst
- inst/rmarkdown/templates/glossa/skeleton/glossa.cls
Fixing error in glossa article when rendering, caused by microtype.
The authors of the `glossa.cls` say in the comments that the microtype LaTeX package is used in production but it's fine if the authors don't have it. So the code loading microtype is now commented out. This solution is a workaround but works both for those using TinyTex and a non-TinyTex installation.
> Update Glossa article

- DESCRIPTION
- NEWS.md
- R/copernicus_article.R
- inst/rmarkdown/templates/copernicus/resources/README_copernicus_package_6_9.txt
- inst/rmarkdown/templates/copernicus/resources/README_copernicus_package_7_1.txt
- inst/rmarkdown/templates/copernicus/resources/template.tex
- inst/rmarkdown/templates/copernicus/skeleton/copernicus.cfg
- inst/rmarkdown/templates/copernicus/skeleton/copernicus.cls
- man/copernicus_article.Rd
Another update to the newest Copernicus template version from September 26 2022.
@nuest
> Copernicus template update to v7.1

- DESCRIPTION
- NEWS.md
- inst/rmarkdown/templates/elsevier/resources/template.tex
- inst/rmarkdown/templates/elsevier/skeleton/skeleton.Rmd
This closes #509 by correctly supporting affiliation fields as explained in the doc and template 
* https://www.elsevier.com/authors/policies-and-guidelines/documents/elsdoc-1.pdf
* https://ctan.crest.fr/tex-archive/macros/latex/contrib/elsarticle/elsarticle-template-harv.tex
````latex
%% use optional labels to link authors explicitly to addresses:
%% \author[label1,label2]{}
%% \affiliation[label1]{organization={},
%%             addressline={},
%%             city={},
%%             postcode={},
%%             state={},
%%             country={}}
%%
%% \affiliation[label2]{organization={},
%%             addressline={},
%%             city={},
%%             postcode={},
%%             state={},
%%             country={}}
````
the skeleton has been updated to show how to pass …
> Support affiliation fields like elsevier template

- DESCRIPTION
- NEWS.md
- inst/rmarkdown/templates/ieee/resources/template.tex
- inst/rmarkdown/templates/ieee/skeleton/skeleton.Rmd
This should solve #500 to allow multiple affiliation using 
````yaml
author:   
- name: Eldon Tyrell
mark: [2, 3]
email: eldon@starfleet-academy.star
````
when `wide: true` is used. 
The template is also update for other mode
> Support multiple institution for author in wide format for IEEE

- inst/rmarkdown/templates/ieee/resources/template.tex
This follows up on #269 
- `natbib` `biblatex` and default pandoc's citeproc should work with the template
- Template correctly use the right variables for customization
> [ieee] Improve bibliography handling

- NEWS.md
- R/copernicus_article.R
- inst/rmarkdown/templates/copernicus/resources/README_copernicus_package_7_5.txt
- inst/rmarkdown/templates/copernicus/skeleton/copernicus.bst
- inst/rmarkdown/templates/copernicus/skeleton/copernicus.cls
- man/copernicus_article.Rd
> Update Copernicus template from 7.3 to 7.5

- DESCRIPTION
- NEWS.md
- inst/rmarkdown/templates/copernicus/resources/README_copernicus_package_7_7.txt
- inst/rmarkdown/templates/copernicus/resources/template.tex
- inst/rmarkdown/templates/copernicus/skeleton/copernicus.cls
It requires update as seen in #558
> Update to Copernicus 7.7

- NEWS.md
- R/copernicus_article.R
- inst/rmarkdown/templates/copernicus/resources/README_copernicus_package_7_8.txt
- inst/rmarkdown/templates/copernicus/resources/template.tex
- inst/rmarkdown/templates/copernicus/skeleton/copernicus.cfg
- man/copernicus_article.Rd
Yet another Copernicus template update + the fix suggested by @colinasmith fixing 
issue #565. Info to @nuest
> Copernicus template update 7.8 + fix #565

- DESCRIPTION
- NEWS.md
- inst/rmarkdown/templates/springer/resources/template.tex
- inst/rmarkdown/templates/springer/skeleton/skeleton.Rmd
Thank you for a providing and maintaining a this great package!
While using the Springer Template, I noticed that the equal contributions line on the fronpage was missing. I have corrected it and tested it in my pull request so it should work now. Further, I have added an option to include ORCID ID at the end of each author line. Ideally, the ORCID ID should be placed after the star and dagger, but doing that is beyond my abilities. Supplying ORCID is not specified in the Springer Nature Template guide; however, some Springer Journals, e.g. the European Journal of Nutrition, accept manuscript submissions based on the Springer Nature Template but also encourages authors to provide ORCID. So I think it makes sense to add it.
I hope these changes are useful. I'm quite new in this field (this …
> Fix equal contribution in Springer template and add ORCID ID

- DESCRIPTION
- R/article.R
From rstudio/rmarkdown#2485
closes #544
> Support new pre_knit feature

- inst/rmarkdown/templates/elsevier/skeleton/skeleton.Rmd
Right now it says
```
classoption: preprint, 3p, authoryear # remove authoryear is not using `elsarticle-harv`
```
I think it should be 
```
classoption: preprint, 3p, authoryear # remove authoryear if not using `elsarticle-harv`
```
is -> if
> Fixing a typo in  a comment in the Elsevier skeleton
